# Base image
FROM ubuntu:18.04

# Unity download path
ARG UNITY_SETUP=https://beta.unity3d.com/download/f007ed779b7a/UnitySetup-2019.1.10f1
ARG UNITY_COMPONENTS=Unity,Windows-Mono

# Add dependencies
RUN set -ex \
    && apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get upgrade -y \
    && DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y \
        curl zip ca-certificates osslsigncode \
        gconf-service lib32gcc1 lib32stdc++6 libasound2 libc6 libc6-i386 libcairo2 libcap2 libcups2 \
        libdbus-1-3 libexpat1 libfontconfig1 libfreetype6 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 \
        libgl1 libglib2.0-0 libglu1 libgtk2.0-0 libgtk-3-0 libnspr4 libnss3 libpango1.0-0 libstdc++6 \
        libx11-6 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 \
        libxrender1 libxtst6 zlib1g debconf npm libgtk2.0-0 libsoup2.4-1 libarchive13 libpng16-16 \
    && apt-get clean \
    && curl -fLo UnitySetup ${UNITY_SETUP} \
    && chmod +x UnitySetup \
    && echo y | ./UnitySetup --unattended --install-location=/opt/Unity --verbose --components=${UNITY_COMPONENTS} \
    && rm UnitySetup

# Copy the unity project to work directroy in container
ADD ../../BuilPipeline /opt/unity_project
WORKDIR /opt/unity_project

# Run unity build script

